version: "3.7"

services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    ports:
      - "8080:10000" # Entrada HTTP
      - "9901:9901" # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy-example.yaml
