version: "3.8"

services:
  service-a:
    build:
      context: ./service-a
    ports:
      - "8081:8081"

  service-b:
    build:
      context: ./service-b
    ports:
      - "8082:8082"

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    ports:
      - "8080:8080" # Entrada pública
      - "9901:9901" # Admin interface
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - service-a
      - service-b
